version: '3.3'
services:
 gsan:
  build: .
  environment:
    - POSTGRES_URL=http://postgres:5432
  ports:
    - "80:8282"
  volumes:
    - /gsan/diskEXT/docker-compose/gsan:/usr/gsan/src/
  depends_on:
    - postgres
 postgres:
   build: ./myPostgresDocker/
   volumes:
     - /gsan/diskEXT/docker-compose/postgres:/var/lib/postgresql/data
