version: '3.3'
services:
 gsan:
  build: .
  environment:
    - POSTGRES_URL=http://postgres:5432
  ports:
    - "8282:8282"
  volumes:
    - /home/aaron/Desktop/test/gsan:/usr/gsan/src/
  depends_on:
    - postgres
 postgres:
   build: ./myPostgresDocker/
   volumes:
     - /home/aaron/Desktop/test/postgres:/var/lib/postgresql/data
