version: '3.3'
services:
   gsan:
       build: .
       environment:
        -POSTGRES_URL=http://postgres:5432
       ports:
        - "8280:8282"
       volumes:
        - /home/aaron/Desktop/test/gsan:.
       depends_on:
        - postgres
   postgress:
     build: ./myPostgresDocker/
     volumes:
      - /home/aaron/Desktop/test/:/var/lib/postgresql/data
