psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER gsan;
CREATE DATABASE gsanprocess;
GRANT ALL PRIVILEGES ON DATABASE gsanprocess TO gsan;
ALTER ROLE gsan WITH PASSWORD 'MdPGSAN01**';
ALTER USER gsan WITH SUPERUSER;
EOSQL

